package lab;
import java.util.Random;

public class mainclass {
static int autogeneratedId() {
	Random rand=new Random();
	int minrange=10000,maxrange=50000;
	int value=rand.nextInt(maxrange-minrange)+minrange;
	return value;
}
public static void main(String[] args) {
	Person s=new Person("smith",53);
	Account accS=new Savings(autogeneratedId(),20,s);
	
	Person k=new Person("kathy",34);
	Account accK=new Savings(autogeneratedId(),30,k);
	
	Person j=new Person("jack",23);
	Account accj=new Savings(autogeneratedId(),5000,j);
	
	accS.deposit(2000);
	accK.withdraw(5000);
	accj.withdraw(50);
}
}